### PR TITLE
Update deployment procedure

### PR DESCRIPTION
**Pull request by dinyar**
This PR adds many configuration files (systemd, udev, auto load for the driver), updates the Readme accordingly and also changes the URL for the reset server.

~~Currently being verified with on the new scouting machine, please don't merge yet.~~

@emeschi, @tj710, @pzejdl I think this is ready for merging now. Can you have a look if things look reasonable to you? The readme is essentially a log of what I did to get the new scoutdaq machine up and running, eventually (almost) all of it should of course be done in the course of an RPM installation.

### CODE REVIEW

**Comment by pzejdl** [comment]
Hi @dinyar,

Very good for making systemd services! We are one step closer to rpm.

But for the rpm we need to re-think if we should store and run the w in user home dir. 

Adding a few comments below.

Best regards,
Petr

**Comment by dinyar** [comment]
> Very good for making systemd services! We are one step closer to rpm.
> 
> But for the rpm we need to re-think if we should store and run the w in user home dir.

Yes, absolutely agree. I think it should go into /opt medium term (and certainly once we move to an RPM), but I don't know well enough how the user situation then would work: Currently at least on -39 I've restricted the sudo rights of `scouter` to the subset of commands that it needs to run `scdaq`, but I'm not sure if this can be also done at RPM install. (In my head the ideal situation would be that as part of the installation a `scouter` or `scdaq` user is created that has the minimal rights necessary to run `scdaq`.. )

**Comment by pzejdl** [comment]
Indeed. Once we move to `/opt/something` I believe the correct way would be creating `scouter` or` scdaq` user directly in the installation script/rpm. It can be lightweight user, i.e. it doesn't need home directory. But them we need to install bitstreams and firmware tools also to `/opt`. But that is probably fine.

About sudo rights let's see with sysadmins on the best approach, they can also be added with puppet.

Do you want to deal with installation to `/opt`in this PR or do you prefer creating a new one?

**Review by tj710 — APPROVED** [review]

**Comment by dinyar** [comment]
I've moved several of these services to https://gitlab.cern.ch/scouting-demonstrator/scouting-hardware-tools where they fit better and Emilio is going to submit a PR (I think) tomorrow with the scdaq service included, so I'm closing this.

**Pull request closed without merging**
