### PR TITLE
Replacing tbb::zero_allocator with aligned allocator

### PR DESCRIPTION
**Pull request by pzejdl**
MicronDMA requires the buffers to be aligned to 32 bytes (256 bits)...

### CODE REVIEW

**Comment by pzejdl** [comment]
@RoccoA97 Could you please test the new allocator with xdma and wz drivers?

**Comment by RoccoA97** [comment]
@pzejdl I have tested with both the drivers. I confirm that the behaviour of the software has not changed. WZDMA works as usual, XDMA works with the same problems

**Comment by pzejdl** [comment]
@RoccoA97 Super, thanks. Btw, did you notice and difference in the DMA bandwidth?

**Comment by RoccoA97** [comment]
@pzejdl DMA bandwidth is the same as well

**Comment by pzejdl** [comment]
Perfect, thanks.

**Review by RoccoA97 — APPROVED** [review]

**Review by tj710 — APPROVED** [review]

**Pull request merged**
